name: eo-learn-docs
channels:
- conda-forge
dependencies:
- cartopy=0.17.0
- pip:
  - Sphinx
  - sphinx-rtd-theme
  - nbsphinx
  - ipython
  - git+https://github.com/CrossNox/m2r@dev

  - ./../core
  - ./../coregistration
  - ./../features
  - ./../geometry
  - ./../io
  - ./../mask
  - ./../ml_tools
  - ./../visualization[FULL]
